export declare const clean: (text: string) => string;
export declare const isEmptyObj: (obj: object) => boolean;
export declare const monthNames: string[];
export declare const monthNamesEn: string[];
export declare const escapeHTML: (text: string, withQuote: boolean) => string;
export declare const specialHTML: (text: string) => string;
export declare const parseURL: (url: string) => string;
export declare const ucwords: (text: string, func?: (str: string) => void) => string | void;
export declare const jsStyles: (text: string, func?: (str: string) => void) => string | void;
export declare const firstLetter: (text: string, number?: number, func?: (str: string) => void) => string | void;
export declare const urlToDomain: (url: string) => string;
export declare const replaceAt: (text: string, index: number, replacement: string) => string;
export declare const truncate: (text: string, num: number) => string;
export declare const splice: (text: string, idx: number, rem: number, str: string) => string;
export declare const slugFormat: (text: string, func?: (result: string) => void, lowercase?: boolean) => string | void;
export declare function copyTextBrowser(text: string): Promise<void>;
export declare const toBlob: (b64Data: string, contentType: string, sliceSize?: number) => Blob;
export declare const number_size: (bytes: number | null | undefined, precision: number) => string;
export declare const generateRandom: () => string;
export declare const numberFormat: (angka: string, separate: string) => string;
export declare const time_ago: (seconds: number) => string;
export declare const insertElementAfter: (newNode: HTMLElement, referenceNode: HTMLElement) => void;
export declare const acronym: (text: string, len?: number) => string;
export declare const separateNumber: (angka: number) => string;
export declare const addslashes: (str: string) => string;
export declare const adddesc: (str: string) => string;
export declare function listToMatrix(list: never[], elementsPerSubArray: number): any[];
export declare const extractMeta: (file: string) => {
    name: string;
    match: RegExpExecArray;
};
export declare const randomInt: (total?: number) => number;
export declare const isURL: (url: string) => boolean;
export declare const isTwitterURL: (url: string) => boolean;
