name: Utils CI

on:
  pull_request:
    branches:
      - main
    paths: 'packages/utils/**'

jobs:
  utils-test:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: 'packages/utils'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Depedencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Test Utils
        run: npm test
